# docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STORAGE_TYPE=s3
      - S3_BUCKET=flashcard-storage
    depends_on:
      - redis
      - postgres
  
  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    command: poetry run celery -A infrastructure.jobs.celery_app worker --loglevel=info
    environment:
      - DEEPL_API_KEY=${DEEPL_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - postgres
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=flashcards
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: